// TSI intake backend version marker: v3 Build 0018
function portalV2ReadProp_(key, fallbackValue) {
  try {
    var value = PropertiesService.getScriptProperties().getProperty(key);
    if (value === null || value === '') return fallbackValue;
    return value;
  } catch (e) {
    return fallbackValue;
  }
}

// Portal V3 runtime defaults.
// Edit these values directly in code for normal operational changes.
// Script Properties are reserved for secrets only (for example Zepto token) unless
// a future operational need justifies moving another setting back out of code.
var PORTAL_V2_RUNTIME_DEFAULTS = {
  SCRIPT: {
    VERSION: 'v3',
    BUILD: '0018',
    SCRIPT_ID: '1M-f5amNTPSb4RZ21gBON0tC6-8pwQMCp0G9G4rx42xBMky1gcX9FtPDy'
  },
  STORAGE: {
    SPREADSHEET_ID: '1hxIaJqfa5O_3vxPNChdfltPkGhsoGpJJiC00ojgV_6c',
    MASTER_SHEET_NAME: 'ALLF',
    ROUTE_SHEETS: {
      government: 'SGOV',
      education: 'SEDU',
      'private-sector': 'SPVT',
      'small-business': 'SSML',
      professional: 'SPRO',
      student: 'SSTU',
      investment: 'PINV',
      press: 'PPRS',
      employment: 'PEMP',
      internship: 'PINT'
    },
    SUPPORT_SHEETS: {
      FAIL: 'FAIL',
      MAIL_LOG: 'MAIL',
      BURST: 'BRST',
      INTERNAL_USERNAME: 'IUSR',
      WRITE_ISSUES: 'WRIT',
      DASHBOARD: 'DASH'
    }
  },
  TEMPLATE_SOURCE: {
    SPREADSHEET_ID: '1X70S4LbfR3ufqLo9sOQEa582sn72uoGJ35ezXpCIrTQ',
    SHEET_NAME: 'live_edit'
  },
  LIMITS: {
    RATE_LIMIT_SECONDS: 30,
    RATE_LIMIT_GLOBAL_MAX: 6,
    RATE_LIMIT_GLOBAL_WINDOW_SECONDS: 10,
    RATE_LIMIT_TRACK_MAX: 3,
    RATE_LIMIT_TRACK_WINDOW_SECONDS: 10,
    DEDUPE_SECONDS: 3600,
    MESSAGE_MAX_LENGTH: 1400,
    FILE_UPLOAD_MAX_BYTES: 8388608
  },
  BEHAVIOR: {
    HONEYPOT_KEY: 'website',
    INTERNAL_EMAIL_DOMAINS_CSV: 'texasskillsinitiative.org,texasskillsinitiative.com',
    SOURCE: 'tsi-portal-v3',
    DASHBOARD_ENABLED: false,
    FAIL_UPLOAD_FOLDER_ID: '18E7iwb-bB8rOUj6BNSZo1JLcAb8TF2Sl',
    WRITE_ISSUE_ALERT_ENABLED: true
  },
  MAIL: {
    ADMIN_NOTIFY_EMAIL: 'intake-notify@texasskillsinitiative.org',
    ZEPTO_API_BASE: 'https://api.zeptomail.com',
    ZEPTO_USE_ROUTE_FROM: false,
    ZEPTO_FROM_DEFAULT: 'howdy@texasskillsinitiative.org',
    ZEPTO_FROM_ROUTE_OVERRIDES: {
      government: '',
      education: '',
      'private-sector': '',
      'small-business': '',
      professional: '',
      student: '',
      investment: '',
      press: '',
      employment: '',
      internship: ''
    },
    ZEPTO_REPLY_TO_DEFAULT: '',
    MAIL_FALLBACK_ENABLED: true,
    FAIL_NOTIFY_ENABLED: true,
    AUTO_REPLY_ENABLED: true,
    AUTO_REPLY_ROUTE_OVERRIDES: {
      government: null,
      education: null,
      'private-sector': null,
      'small-business': null,
      professional: null,
      student: null,
      investment: null,
      press: null,
      employment: null,
      internship: null
    },
    AUTO_REPLY_SUBJECT_PREFIX: 'TSI Intake Confirmation',
    AUTO_REPLY_SIGNATURE: 'TSI Intake Team'
  }
};

var PORTAL_V2_CONFIG = {
  VERSION: PORTAL_V2_RUNTIME_DEFAULTS.SCRIPT.VERSION,
  BUILD: PORTAL_V2_RUNTIME_DEFAULTS.SCRIPT.BUILD,
  SCRIPT_ID: PORTAL_V2_RUNTIME_DEFAULTS.SCRIPT.SCRIPT_ID,

  SPREADSHEET_ID: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.SPREADSHEET_ID,
  MASTER_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.MASTER_SHEET_NAME,
  ROUTE_SHEETS: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.ROUTE_SHEETS,

  INVESTMENT_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.ROUTE_SHEETS.investment,
  PRESS_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.ROUTE_SHEETS.press,
  EMPLOYMENT_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.ROUTE_SHEETS.employment,
  INTERNSHIP_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.ROUTE_SHEETS.internship,
  STAKEHOLDER_MASTER_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.MASTER_SHEET_NAME,

  TEMPLATE_SHEET_ID: PORTAL_V2_RUNTIME_DEFAULTS.TEMPLATE_SOURCE.SPREADSHEET_ID,
  TEMPLATE_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.TEMPLATE_SOURCE.SHEET_NAME,

  RATE_LIMIT_SECONDS: PORTAL_V2_RUNTIME_DEFAULTS.LIMITS.RATE_LIMIT_SECONDS,
  RATE_LIMIT_GLOBAL_MAX: PORTAL_V2_RUNTIME_DEFAULTS.LIMITS.RATE_LIMIT_GLOBAL_MAX,
  RATE_LIMIT_GLOBAL_WINDOW_SECONDS: PORTAL_V2_RUNTIME_DEFAULTS.LIMITS.RATE_LIMIT_GLOBAL_WINDOW_SECONDS,
  RATE_LIMIT_TRACK_MAX: PORTAL_V2_RUNTIME_DEFAULTS.LIMITS.RATE_LIMIT_TRACK_MAX,
  RATE_LIMIT_TRACK_WINDOW_SECONDS: PORTAL_V2_RUNTIME_DEFAULTS.LIMITS.RATE_LIMIT_TRACK_WINDOW_SECONDS,
  DEDUPE_SECONDS: PORTAL_V2_RUNTIME_DEFAULTS.LIMITS.DEDUPE_SECONDS,
  BURST_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.SUPPORT_SHEETS.BURST,
  MESSAGE_MAX_LENGTH: PORTAL_V2_RUNTIME_DEFAULTS.LIMITS.MESSAGE_MAX_LENGTH,
  FILE_UPLOAD_MAX_BYTES: PORTAL_V2_RUNTIME_DEFAULTS.LIMITS.FILE_UPLOAD_MAX_BYTES,

  INVESTMENT_UPLOAD_FOLDER_ID: '',
  PRESS_UPLOAD_FOLDER_ID: '',
  EMPLOYMENT_UPLOAD_FOLDER_ID: '',
  INTERNSHIP_UPLOAD_FOLDER_ID: '',
  PORTAL_UPLOAD_FOLDER_ID: '1KGLpDjlj9kZ-XpGlY856RKV4ZK6AeZUx',
  STAKEHOLDER_UPLOAD_FOLDER_ID: '',

  HONEYPOT_KEY: PORTAL_V2_RUNTIME_DEFAULTS.BEHAVIOR.HONEYPOT_KEY,
  FAIL_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.SUPPORT_SHEETS.FAIL,
  FAIL_UPLOAD_FOLDER_ID: PORTAL_V2_RUNTIME_DEFAULTS.BEHAVIOR.FAIL_UPLOAD_FOLDER_ID,
  INTERNAL_USERNAME_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.SUPPORT_SHEETS.INTERNAL_USERNAME,
  INTERNAL_EMAIL_DOMAINS_CSV: PORTAL_V2_RUNTIME_DEFAULTS.BEHAVIOR.INTERNAL_EMAIL_DOMAINS_CSV,
  SOURCE: PORTAL_V2_RUNTIME_DEFAULTS.BEHAVIOR.SOURCE,
  DASHBOARD_ENABLED: !!PORTAL_V2_RUNTIME_DEFAULTS.BEHAVIOR.DASHBOARD_ENABLED,
  WRITE_ISSUES_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.SUPPORT_SHEETS.WRITE_ISSUES,
  DASHBOARD_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.SUPPORT_SHEETS.DASHBOARD,
  WRITE_ISSUE_ALERT_ENABLED: !!PORTAL_V2_RUNTIME_DEFAULTS.BEHAVIOR.WRITE_ISSUE_ALERT_ENABLED,

  ADMIN_NOTIFY_EMAIL: PORTAL_V2_RUNTIME_DEFAULTS.MAIL.ADMIN_NOTIFY_EMAIL,
  ZEPTO_TOKEN: portalV2ReadProp_('PORTAL_V2_ZEPTO_TOKEN', ''),
  ZEPTO_API_BASE: PORTAL_V2_RUNTIME_DEFAULTS.MAIL.ZEPTO_API_BASE,
  ZEPTO_USE_ROUTE_FROM: !!PORTAL_V2_RUNTIME_DEFAULTS.MAIL.ZEPTO_USE_ROUTE_FROM,
  ZEPTO_FROM_DEFAULT: PORTAL_V2_RUNTIME_DEFAULTS.MAIL.ZEPTO_FROM_DEFAULT,
  ZEPTO_FROM_ROUTE_OVERRIDES: PORTAL_V2_RUNTIME_DEFAULTS.MAIL.ZEPTO_FROM_ROUTE_OVERRIDES,
  ZEPTO_REPLY_TO_DEFAULT: PORTAL_V2_RUNTIME_DEFAULTS.MAIL.ZEPTO_REPLY_TO_DEFAULT,
  MAIL_LOG_SHEET_NAME: PORTAL_V2_RUNTIME_DEFAULTS.STORAGE.SUPPORT_SHEETS.MAIL_LOG,
  MAIL_FALLBACK_ENABLED: !!PORTAL_V2_RUNTIME_DEFAULTS.MAIL.MAIL_FALLBACK_ENABLED,
  FAIL_NOTIFY_ENABLED: !!PORTAL_V2_RUNTIME_DEFAULTS.MAIL.FAIL_NOTIFY_ENABLED,

  AUTO_REPLY_ENABLED: !!PORTAL_V2_RUNTIME_DEFAULTS.MAIL.AUTO_REPLY_ENABLED,
  AUTO_REPLY_ROUTE_OVERRIDES: PORTAL_V2_RUNTIME_DEFAULTS.MAIL.AUTO_REPLY_ROUTE_OVERRIDES,
  AUTO_REPLY_SUBJECT_PREFIX: PORTAL_V2_RUNTIME_DEFAULTS.MAIL.AUTO_REPLY_SUBJECT_PREFIX,
  AUTO_REPLY_SIGNATURE: PORTAL_V2_RUNTIME_DEFAULTS.MAIL.AUTO_REPLY_SIGNATURE
};

var PORTAL_V2_COLUMNS = [
  'received_utc', 'client_tz', 'client_utc_offset_minutes', 'rout',
  'name', 'email', 'org', 'role', 'loc_city', 'loc_state', 'loc_country',
  'focus',
  'pinv_stage', 'pinv_check_range', 'pinv_geography', 'pinv_focus', 'pinv_timeline', 'pinv_investor_type', 'pinv_investor_type_other',
  'pprs_outlet', 'pprs_role', 'pprs_deadline', 'pprs_topic', 'pprs_format',
  'pemp_role_interest', 'pemp_timeline', 'pemp_location_pref',
  'pint_school', 'pint_program', 'pint_grad_date', 'pint_track', 'pint_mode',
  'pint_hours_per_week', 'pint_start_date', 'pint_portfolio_url',
  'message', 'attachment_name', 'attachment_type', 'attachment_size', 'attachment_url', 'attachment_status',
  'source', 'page_path', 'referrer', 'submission_id'
];
